#!/usr/bin/env python3
import argparse,itertools,json,os
from fractions import Fraction as F

AUDITS=('character-composition','history-order','scale-nonuniqueness','amplitude-sensitivity')
PERMS=list(itertools.permutations(range(4)))
C=[[F(0) if i==j else F(1) for j in range(4)] for i in range(4)]
RS=[F(3,2),F(4,3),F(5,4),F(7,5),F(8,7),F(9,8)]

def G_from_counts(n,r):
    s=[r**int(x) for x in n]
    return [[C[i][j]*s[i]*s[j] for j in range(4)] for i in range(4)]

def flat(G): return tuple(x for row in G for x in row)

def audit_character(lane):
    r=RS[lane]
    maxn=8
    # Refinement-compatible multiplicative character generated by one event value r.
    comp=all(r**(n+m)==(r**n)*(r**m) for n in range(maxn+1) for m in range(maxn+1-n))
    unit=(r**0==1)
    # Exact induction certificate in exponent form: e(0)=0 and e(n+1)=e(n)+1 => e(n)=n.
    e=[0]
    for _ in range(maxn): e.append(e[-1]+1)
    induction=(e==list(range(maxn+1)))
    # S4 makes the four generator characters share the same r when generator labels carry no extra datum.
    generator_values=[r]*4
    s4_equal=(len(set(generator_values))==1)
    passed=comp and unit and induction and s4_equal
    return {
      'gate':'ITER016-G16-BOOLEAN-REFINEMENT-CHARACTER','audit':'character-composition','lane':lane,
      'r':str(r),'max_count_checked':maxn,'multiplicative_composition_exact':comp,'unit_exact':unit,
      'integer_character_induction_certificate':induction,'s4_common_generator_value':s4_equal,'passed':passed,
      'classification':'PASS_SCOPED_IF_REPEATED_GENERATOR_EVENTS_ARE_COMPOSED_MULTIPLICATIVELY_ACROSS_REFINEMENT_THEN_S4_REDUCES_THE_GENERATOR_LOCAL_RESCALE_FAMILY_TO_ONE_COMMON_CHARACTER_PARAMETER_R',
      'guard':'The Boolean cell itself contains each generator at most once; the repeated-count law is a refinement-composition hypothesis, not an independently derived new microscopic law.'
    }

def audit_history(lane):
    r=RS[lane]
    endpoints=[]
    for p in PERMS:
        n=[0,0,0,0]
        for d in p:n[d]+=1
        endpoints.append(flat(G_from_counts(n,r)))
    order_independent=(len(set(endpoints))==1)
    weight_sum=sum(F(1,24) for _ in PERMS)
    passed=order_independent and weight_sum==1
    return {
      'gate':'ITER016-G16-HISTORY-ORDER-INDEPENDENCE','audit':'history-order','lane':lane,'r':str(r),
      'history_count':len(PERMS),'distinct_final_G':len(set(endpoints)),'history_weight_sum':str(weight_sum),
      'passed':passed,
      'classification':'PASS_SCOPED_ALL_24_BOOLEAN_ORDERINGS_HAVE_THE_SAME_FRAME_RESCALE_ENDPOINT_FOR_ARBITRARY_COMMON_R_AND_EXISTING_EQUAL_HISTORY_WEIGHTS_REMAIN_NORMALIZED',
      'interpretation':'History-order symmetry and completeness are therefore blind to the absolute value of r.'
    }

def audit_nonunique(lane):
    r1=RS[lane];r2=RS[(lane+1)%len(RS)]
    n=(1,1,1,1)
    g1=G_from_counts(n,r1);g2=G_from_counts(n,r2)
    distinct=(g1!=g2)
    # Both satisfy all algebraic composition and S4 endpoint rules.
    comp1=all(r1**(a+b)==r1**a*r1**b for a in range(4) for b in range(4))
    comp2=all(r2**(a+b)==r2**a*r2**b for a in range(4) for b in range(4))
    passed=distinct and comp1 and comp2
    return {
      'gate':'ITER016-G16-COMMON-R-NONUNIQUENESS','audit':'scale-nonuniqueness','lane':lane,
      'r1':str(r1),'r2':str(r2),'distinct_final_G':distinct,'both_composition_exact':comp1 and comp2,
      'passed':passed,
      'classification':'BLOCKED_SCOPED_BOOLEAN_REFINEMENT_COMPOSITION_AND_S4_DO_NOT_FIX_THE_COMMON_CHARACTER_VALUE_R__MULTIPLE_EXACT_R_VALUES_OBEY_ALL_TESTED_RULES_BUT_GIVE_DISTINCT_PHYSICAL_G_ENDPOINTS',
      'interpretation':'The functional ambiguity is reduced to one scalar event scale, but that scalar is still an unfixed UV datum.'
    }

def audit_amplitude(lane):
    r1=RS[lane];r2=RS[(lane+2)%len(RS)]
    q1=r1-1;q2=r2-1
    # Same finite one-step profile proxy used in G15: a two-derivative local action is homogeneous quadratic in first differences at leading order.
    profile1=q1*q1;profile2=q2*q2
    # G13 cubic basis responses for equal two/three-event activations, kept symbolically as coefficient rows times powers of q.
    pair_row1=(q1*q1,2*q1*q1*q1,F(0));pair_row2=(q2*q2,2*q2*q2*q2,F(0))
    triple_connected1=q1*q1*q1;triple_connected2=q2*q2*q2
    different=(profile1!=profile2 and pair_row1!=pair_row2 and triple_connected1!=triple_connected2)
    # Existing equal history completeness has no r-equation.
    history_norm=sum(F(1,24) for _ in range(24))
    passed=different and history_norm==1
    return {
      'gate':'ITER016-G16-AMPLITUDE-SENSITIVITY-TO-R','audit':'amplitude-sensitivity','lane':lane,
      'r1':str(r1),'r2':str(r2),'q1':str(q1),'q2':str(q2),'profile_quadratic':[str(profile1),str(profile2)],
      'g13_pair_basis_rows':[[str(x) for x in pair_row1],[str(x) for x in pair_row2]],
      'connected_triple_scale':[str(triple_connected1),str(triple_connected2)],'history_weight_sum':str(history_norm),
      'passed':passed,
      'classification':'BLOCKED_SCOPED_ABSOLUTE_FINITE_PROFILE_AND_PAIR_TRIPLE_AMPLITUDE_SCALES_DEPEND_ON_THE_UNFIXED_COMMON_CHARACTER_R_WHILE_HISTORY_NORMALIZATION_SUPPLIES_NO_EQUATION_FOR_R',
      'guard':'This establishes scale sensitivity and non-identifiability, not a full microscopic finite action formula.'
    }

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--audit',choices=AUDITS,required=True);ap.add_argument('--lane',type=int,required=True);ap.add_argument('--out',required=True)
    a=ap.parse_args();assert 0<=a.lane<6
    fn={'character-composition':audit_character,'history-order':audit_history,'scale-nonuniqueness':audit_nonunique,'amplitude-sensitivity':audit_amplitude}[a.audit]
    out=fn(a.lane);os.makedirs(os.path.dirname(a.out),exist_ok=True)
    with open(a.out,'w') as f:json.dump(out,f,indent=2,sort_keys=True)
    print(json.dumps(out,sort_keys=True))
    if not out['passed']:raise SystemExit(1)
if __name__=='__main__':main()
