#!/usr/bin/env python3
import argparse,itertools,json
P=argparse.ArgumentParser();P.add_argument('--output',required=True);args=P.parse_args();D=4
A=(0,0,0,0);B=(1,0,0,0)
def vertices(base):return {tuple(base[i]+b[i] for i in range(D)) for b in itertools.product([0,1],repeat=D)}
def edges(base):
 out=set()
 for d in range(D):
  for bits in itertools.product([0,1],repeat=D-1):
   x=list(base);q=0
   for j in range(D):
    if j==d:continue
    x[j]+=bits[q];q+=1
   out.add((tuple(x),d))
 return out
VA,VB=vertices(A),vertices(B);EA,EB=edges(A),edges(B);VF=VA&VB;EF=EA&EB
# Expand each vertex into 10 response-coordinate labels and each edge into 6 connection-fiber labels.
def coords(V,E):
 return {('G',v,a) for v in V for a in range(10)}|{('A',e,a) for e in E for a in range(6)}
CA,CB,CF=coords(VA,EA),coords(VB,EB),coords(VF,EF)
assert CA&CB==CF
assert (len(CA),len(CB),len(CF),len(CA|CB))==(352,352,152,552)
# Coordinate cylinder multiplication algebras: polynomial monomials supported only on region coordinates.
# A monomial lies in both iff all its variables are in the coordinate-set intersection.
test_monomials=[frozenset(x) for x in itertools.combinations(sorted(CA|CB,key=str),2)]
for m in test_monomials:
 inA=m<=CA;inB=m<=CB
 if inA and inB: assert m<=CF
# Disjoint exclusive coordinate generators commute as multiplication operators; overlap is shared, not duplicated.
exclusiveA=CA-CF;exclusiveB=CB-CF
assert exclusiveA.isdisjoint(exclusiveB) and exclusiveA.isdisjoint(CF) and exclusiveB.isdisjoint(CF)
out={
 'lane':'CYLINDRICAL_ALGEBRA_INTERSECTION',
 'linear_coordinate_dimensions':{'A':len(CA),'B':len(CB),'intersection':len(CF),'union':len(CA|CB)},
 'exact_coordinate_intersection':'C_A intersect C_B = C_shared_B3',
 'polynomial_cylinder_intersection':'For free polynomial multiplication observables generated by primitive regular coordinates, Alg(A) intersect Alg(B)=Alg(shared B3).',
 'exclusive_coordinate_sets_disjoint':True,
 'classification':'PASS_SCOPED_CYLINDRICAL_MULTIPLICATION_NET_HAS_EXACT_B3_INTERSECTION_AND_DOES_NOT_DUPLICATE_OVERLAP_DEGREES_OF_FREEDOM',
 'scientific_interpretation':'At the regular finite configuration level, observables depending only on the shared response/edge coordinates belong to both local cylindrical algebras, while exclusive A and B coordinate generators are distinct. This gives an exact local-net intersection theorem for the multiplication/cylindrical subalgebra.',
 'guard':'This is not a theorem that the full interacting gauge-invariant operator algebras satisfy Haag duality, split property, or tensor factorization. Momentum/derivation operators and constraints can couple through the common boundary.'
}
open(args.output,'w').write(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,sort_keys=True))
