#!/usr/bin/env python3
import argparse,json
P=argparse.ArgumentParser();P.add_argument('--output',required=True);args=P.parse_args()
# B4 combinatorics fix dimensionless counts only.
counts={'vertices':16,'oriented_cover_edges':32,'rank2_unordered_pairs':6,'maximal_histories':24,'directions':4}
lambdas=[0.25,0.5,1.0,2.0,4.0]
rows=[]
for lam in lambdas:
    rows.append({'lambda':lam,'cell_spacing_ratio':lam,'same_B4_counts':counts,'same_history_count':24,'same_S4_group_order':24})
assert all(r['same_B4_counts']==counts for r in rows)
out={
 'lane':'B4_COMBINATORIAL_SCALE_AUDIT',
 'dimensionless_B4_data':counts,
 'rows':rows,
 'classification':'BLOCKED_SCOPED_B4_INCIDENCE_HISTORY_AND_S4_COMBINATORICS_FIX_DIMENSIONLESS_STRUCTURE_BUT_NOT_AN_ABSOLUTE_PHYSICAL_CELL_LENGTH',
 'scientific_interpretation':'The Boolean cell fixes the number of directions, incidence relations, maximal histories and symmetry factors, but all of these data are unchanged under a global rescaling of the physical embedding h. Combined with the G7A kappa->lambda^2 kappa matching freedom, the current finite combinatorics do not select one physical lattice spacing.',
 'guard':'This does not rule out a future scale generated by an additional microscopic spectrum, clock, amplitude quantization or dynamical fixed point. It rules out extracting an absolute length from the present finite counts alone.'
}
open(args.output,'w').write(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,sort_keys=True))