#!/usr/bin/env python3
import argparse,json
import numpy as np
P=argparse.ArgumentParser();P.add_argument('--output',required=True);args=P.parse_args()
rng=np.random.default_rng(7016)
n=24;d=11
X=rng.normal(size=(d,n))+1j*rng.normal(size=(d,n))
X/=np.linalg.norm(X,axis=0,keepdims=True)
rho=X@X.conj().T/n
purity_direct=float(np.real(np.trace(rho@rho)))
Gram=X.conj().T@X
purity_gram=float(np.sum(np.abs(Gram)**2)/(n*n))
assert abs(purity_direct-purity_gram)<1e-12
perm=rng.permutation(n);Gp=Gram[np.ix_(perm,perm)]
purity_perm=float(np.sum(np.abs(Gp)**2)/(n*n))
assert abs(purity_perm-purity_gram)<1e-12
assert 1/n-1e-12<=purity_direct<=1+1e-12
out={
 'lane':'CONDITIONAL_HISTORY_MIXTURE_PURITY_IDENTITY',
 'history_count':n,
 'test_common_hilbert_dimension':d,
 'purity_direct':purity_direct,
 'purity_from_branch_gram':purity_gram,
 'identity':'For normalized branch vectors psi_a in one positive Hilbert space and equal weights 1/N, Tr(rho^2)=N^-2 sum_ab |<psi_a|psi_b>|^2.',
 'branch_permutation_invariant':True,
 'bounds':'1/N <= purity <= 1',
 'classification':'PASS_MATHEMATICAL_IDENTITY_CONDITIONAL_ON_COMMON_POSITIVE_CURVED_PHYSICAL_PAIRING',
 'scientific_interpretation':'Once QGR supplies a common positive physical pairing for the 24 curved branch wavepackets, normalized history forgetting fixes the output purity with no extra decoherence coefficient and no preferred branch basis. All model dependence is then in the branch states generated by QGR transport plus the experimentally specified input preparation.',
 'guard':'This is deliberately conditional. G6C/G8D do not yet provide the required generic curved positive vector inner product, so the identity is not yet a closed QGR numerical purity prediction.'
}
open(args.output,'w').write(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,sort_keys=True))
