#!/usr/bin/env python3
from fractions import Fraction
from itertools import permutations

# QGR Iter003-G5: minimal quadratic action generated by existing B4 rank-2
# pair events. No continuum metric or Einstein-Hilbert action is inserted.

d=4
C=[[Fraction(0 if i==j else 1) for j in range(d)] for i in range(d)]  # J-I


def mv(A,v):
    return [sum(A[i][j]*v[j] for j in range(len(v))) for i in range(len(A))]


def quadratic(A,v):
    Av=mv(A,v)
    return sum(v[i]*Av[i] for i in range(len(v)))

# S4 invariance of the pair-incidence Hessian.
for p in permutations(range(4)):
    CP=[[C[i][p[j]] for j in range(4)] for i in range(4)]
    PTCP=[[CP[p[i]][j] for j in range(4)] for i in range(4)]
    assert PTCP == C

# Every elementary generator direction is exactly characteristic/null.
for i in range(4):
    e=[Fraction(0)]*4
    e[i]=Fraction(1)
    assert quadratic(C,e) == 0

# Signature audit.
ones=[Fraction(1)]*4
assert mv(C,ones) == [Fraction(3)]*4
for u in ([1,-1,0,0],[0,1,-1,0],[0,0,1,-1]):
    u=[Fraction(x) for x in u]
    assert mv(C,u) == [-x for x in u]
# eigenvalues (3,-1,-1,-1)

# In orthonormal decomposition p=p0*(1,1,1,1)/2+p_perp,
# K(p)=3 p0^2-|p_perp|^2. Check algebra on representative rational vectors.
def K_formula(p):
    s=sum(p)
    return s*s - sum(x*x for x in p)
for p in ([1,0,0,0],[1,1,0,0],[1,-1,0,0],[1,2,3,4]):
    p=[Fraction(x) for x in p]
    assert quadratic(C,p) == K_formula(p)

# Two TT-like internal components share this directional Hessian because G2
# proved the internal S4 commutant is one-dimensional. No polarization split.

print({
    'linearized_action': 'S2=(kappa/2) sum_cell Dq^T (J-I) Dq',
    'microscopic_origin': 'equal-weight existing B4 rank-2 distinct-pair events',
    'directional_hessian': 'J-I',
    'principal_eigenvalues': ['3','-1','-1','-1'],
    'hyperbolic': True,
    'four_elementary_directions_null': True,
    'relative_directional_coefficients': 0,
    'overall_kappa': 1,
    'two_TT_like_polarizations_degenerate': True,
    'onsite_mass_term_included': False,
    'onsite_mass_term_forbidden_by_derived_symmetry': False,
    'nonlinear_completion_derived': False,
})
