#!/usr/bin/env python3
import argparse, json
import numpy as np
from qgr_iter011_g3_common import generic_local_stats, logslope

POINTS=[
 [0.05,0.08,-0.04,0.07],
 [0.08,-0.03,0.06,-0.05],
 [-0.06,0.05,0.09,0.03],
 [0.04,-0.07,-0.05,0.08],
]
SPACINGS=np.array([0.12,0.09,0.07,0.055,0.043,0.034,0.027,0.021,0.017,0.0135],float)

def even_value(h,k,y0):
    p=generic_local_stats(float(h),k,y0)
    m=generic_local_stats(float(h),-k,y0)
    return 0.5*(p['delta_log_coarea_local']+m['delta_log_coarea_local']), min(p['min_sv'],m['min_sv']), max(p['residual'],m['residual'])

def polyfit_series(a,y,n,order=5):
    a=np.asarray(a[-n:],float); y=np.asarray(y[-n:],float)
    powers=np.arange(2,order+1)
    X=np.column_stack([a**p for p in powers])
    c,*_=np.linalg.lstsq(X,y,rcond=None)
    pred=X@c
    scale=max(float(np.max(np.abs(y))),1e-30)
    rel=float(np.sqrt(np.mean((pred-y)**2))/scale)
    return {f'c{int(p)}':float(v) for p,v in zip(powers,c)} | {'rms_rel':rel,'n':int(n)}

ap=argparse.ArgumentParser()
ap.add_argument('--point',type=int,required=True)
ap.add_argument('--kappa',type=float,required=True)
a=ap.parse_args()
y0=POINTS[a.point]; k=abs(a.kappa)
rows=[]
for h in SPACINGS:
    y,sv,res=even_value(h,k,y0)
    rows.append({'a':float(h),'coarea_even':float(y),'min_sv':float(sv),'max_residual':float(res)})

xs=np.array([r['a'] for r in rows]); ys=np.array([r['coarea_even'] for r in rows])
fits={str(n):polyfit_series(xs,ys,n) for n in [6,8,10]}
c2=np.array([fits[str(n)]['c2'] for n in [6,8,10]])
c2_scale=max(abs(float(c2[-1])),1e-30)
c2_spread=float((np.max(c2)-np.min(c2))/c2_scale)
p_all=logslope(xs,ys); p_tail=logslope(xs[-4:],ys[-4:])
# Compare explicit no-a^2 model on the same full window.
X_no2=np.column_stack([xs**p for p in [3,4,5]])
c_no2,*_=np.linalg.lstsq(X_no2,ys,rcond=None)
pred_no2=X_no2@c_no2
rms_no2=float(np.sqrt(np.mean((pred_no2-ys)**2))/max(float(np.max(np.abs(ys))),1e-30))
rms_with2=fits['10']['rms_rel']
assert min(r['min_sv'] for r in rows)>0.25
assert max(r['max_residual'] for r in rows)<1e-9
assert np.isfinite(list(c2)+[p_all,p_tail,rms_no2,rms_with2]).all()
if abs(fits['10']['c2'])>1e-18 and c2_spread<0.35 and rms_with2 < max(0.5*rms_no2,1e-14):
    cls='STABLE_NONZERO_TWO_DERIVATIVE_COEFFICIENT_SUPPORTED'
elif rms_with2 < rms_no2:
    cls='TWO_DERIVATIVE_TERM_FAVORED_BUT_NOT_YET_STABLE'
else:
    cls='NO_STABLE_TWO_DERIVATIVE_COEFFICIENT_RESOLVED'
out={
 'gate':'ITER011-G5-GENERIC-LOCAL-SERIES-DECOMPOSITION',
 'point_index':a.point,'y0':y0,'kappa_abs':k,'rows':rows,'fits':fits,
 'single_power_all':float(p_all),'single_power_tail4':float(p_tail),
 'c2_relative_spread':c2_spread,
 'rms_rel_with_a2_to_a5':rms_with2,'rms_rel_without_a2':rms_no2,
 'classification':cls,
 'interpretation':'Tests whether the apparent noninteger single-power exponent is a finite-spacing crossover generated by an ordinary local series beginning at a^2. The a^2 coefficient is inferred independently across nested fit windows; no exponent threshold is retuned to force PASS.',
 'guard':'Scoped weak-background lattice/coarea diagnostic only. A stable c2 identifies a local two-derivative measure contribution in this discretization; it is not a covariant counterterm derivation and says nothing about the missing coherent Lorentzian phase datum.'
}
print(json.dumps(out,sort_keys=True))
